# Generated by Django 5.1 on 2024-10-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='add_date',
            new_name='adate',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='upp_date',
            new_name='udate',
        ),
    ]
